bloodbank/urls.py
from django.urls import path
from .views import (
    IndexView, 
    DonorView, 
    BloodBankHistory, 
    LoginView, 
    DonationCreateView, 
    CampScheduleView,
    CampScheduleDeleteView,
    CampScheduleUpdateView,
    CampScheduleDisplayView,
    UserSignupFromBloodbankView,
    SignupView,
    # BloodCountListView,
    LogoutView,
    BloodBankProfileView,
    BloodBankProfileUpdateView,
    BloodBankLogoUpdateView,
    )


urlpatterns = [

    path('index/<int:pk>/', IndexView.as_view(), name='index1'),

    path('donor-detail/', DonorView.as_view(), name='donordetail'),

    path('bloodbank-history/<int:pk>/', BloodBankHistory.as_view(), name='bloodbank_history'),

    path('login/', LoginView.as_view(), name="bloodbank_signin"),

    path('signup/', SignupView.as_view(), name="bloodbank_signup"),

    path('donation/form/', DonationCreateView.as_view(), name='donation_form'),

    path('camp-schedule/form/', CampScheduleView.as_view(), name='camp_form'),

    path('camp-schedule-update/update/<int:pk>/', CampScheduleUpdateView.as_view(), name='camp_update'),

    path('camp-schedule-delete/delete/<int:pk>/', CampScheduleDeleteView.as_view(), name='camp_delete'),

    path('camp-schedule/', CampScheduleDisplayView.as_view(), name='camp_display'),

    path('user-signup-bloodbank/', UserSignupFromBloodbankView.as_view(), name='user_signup_bloodbank'),
    # path('bloodbank-count/<int:pk>/', BloodCountListView.as_view(), name='blood'),
    path('bloodbank-profile/<int:pk>/', BloodBankProfileView.as_view(), name='bloodbank_profile'),
    path('bloodbank-profile-update/<int:pk>/', BloodBankProfileUpdateView.as_view(), name='bloodbank_profile_update'),
    path('bloodbank-logo-update/<int:pk>/', BloodBankLogoUpdateView.as_view(), name='bloodbank_logo_update'),
    path('bloodbank-logout/', LogoutView.as_view(), name='bloodbank_logout'),

]

blooddrop/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('accounts_app.urls')),
    path('bloodbank/',include('bloodbank.urls'))
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts_app/models.py
from django.db import models
from django.contrib.auth.models import  AbstractBaseUser
from .manager import UserManager
from  phonenumber_field.modelfields import PhoneNumberField
from blooddrop.models import Address

class User(AbstractBaseUser, Address):
  
    username = None
    name = models.CharField(max_length=20)
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True,db_index=True)
    phone_number = PhoneNumberField(db_index=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    otp_create_at = models.DateTimeField(null=True, blank=True)
    otp = models.IntegerField(null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    weight= models.IntegerField(null=True, blank=True)
    is_bloodbank = models.BooleanField(default=False, null=True, blank=True)
    logo = models.ImageField(upload_to='bloodbank_logo/', null=True, blank=True)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin
    
    @property
    def group(self):
        blood_group = getattr(self, "blood_group", None)
        if blood_group:
            return blood_group.blood_group
    
class BloodGroup(models.Model):
    A_POSITIVE = 'A+'
    A_NEGATIVE = 'A-'
    B_POSITIVE = 'B+'
    B_NEGATIVE = 'B-'
    O_POSITIVE = 'O+'
    O_NEGATIVE = 'O-'
    AB_POSITIVE = 'AB+'
    AB_NEGATIVE = 'AB-'
    
    BLOOD_GROUP_CHOICES = [
        (A_POSITIVE, 'A+'),
        (A_NEGATIVE, 'A-'),
        (B_POSITIVE, 'B+'),
        (B_NEGATIVE, 'B-'),
        (O_POSITIVE, 'O+'),
        (O_NEGATIVE, 'O-'),
        (AB_POSITIVE, 'AB+'),
        (AB_NEGATIVE, 'AB-'),
    ]
    
    user = models.OneToOneField(User, related_name='blood_group', on_delete=models.CASCADE)
    blood_group = models.CharField(max_length=3, choices=BLOOD_GROUP_CHOICES)

REQUEST_STATUS_CHOICES = [    ('Pending', 'Pending'),    ('Accepted', 'Accepted'),    ('Rejected', 'Rejected')]
class BloodRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bloodbank = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blood_requests')
    blood_group = models.CharField(max_length=3, choices=BloodGroup.BLOOD_GROUP_CHOICES)
    quantity = models.IntegerField()
    status = models.CharField(choices=REQUEST_STATUS_CHOICES, max_length=10, default='Pending')
    requested_at = models.DateTimeField(auto_now_add=True)

bloodbank/models.py
from django.db import models
from accounts_app.models import User
from blooddrop.models import BaseModel, Address
from datetime import datetime
from  phonenumber_field.modelfields import PhoneNumberField
from django.db.models import Count



class BloodBank(BaseModel, Address):
    user = models.OneToOneField(User, related_name='bloodbank', on_delete=models.CASCADE)
    iso_certified = models.BooleanField(default=False)
    certificate = models.FileField(upload_to='cirtificate', max_length=100)
    logo = models.ImageField(upload_to='bloodbank_logo/', null=True, blank=True)

    class Meta:
        verbose_name = "Blood Bank"
        verbose_name_plural = "Blood Banks"

    def __str__(self):
        return str(self.user.name)
    
class CampSchedule(models.Model):
    bloodbank = models.ForeignKey(BloodBank, related_name='schedule', on_delete=models.CASCADE)
    date = models.DateTimeField()
    starttime = models.TimeField()
    endtime = models.TimeField()
    address = models.TextField()
    pincode = models.IntegerField()

    class Meta:
        verbose_name = "Schedule"
        verbose_name_plural = "Schedules"

    def __str__(self):
        return str(self.date)
    

class Donation(models.Model):
    donor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='donation')
    donation_date = models.DateTimeField(default=datetime.now)
    bloodbank = models.ForeignKey(BloodBank, related_name='donation', on_delete=models.CASCADE)

    class Meta:
        get_latest_by = '-donation_date'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        blood_type = self.donor.blood_group.blood_group
        Blood.objects.create(bloodbank=self.bloodbank, donation=self, type=blood_type)


class Blood(models.Model):
    A_POSITIVE = 'A+'
    A_NEGATIVE = 'A-'
    B_POSITIVE = 'B+'
    B_NEGATIVE = 'B-'
    O_POSITIVE = 'O+'
    O_NEGATIVE = 'O-'
    AB_POSITIVE = 'AB+'
    AB_NEGATIVE = 'AB-'
    
    BLOOD_GROUP_CHOICES = [
        (A_POSITIVE, 'A+'),
        (A_NEGATIVE, 'A-'),
        (B_POSITIVE, 'B+'),
        (B_NEGATIVE, 'B-'),
        (O_POSITIVE, 'O+'),
        (O_NEGATIVE, 'O-'),
        (AB_POSITIVE, 'AB+'),
        (AB_NEGATIVE, 'AB-'),
    ]
    
    bloodbank = models.ForeignKey(BloodBank, related_name='bloods', on_delete=models.CASCADE)
    donation = models.ForeignKey(Donation, related_name='bloods', on_delete=models.CASCADE, null=True, blank=True)
    type = models.CharField(max_length=3, choices=BLOOD_GROUP_CHOICES)

class Request(BaseModel, Address):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = PhoneNumberField(db_index=True)

blooddrop/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract  = True


class Address(models.Model):
    address = models.TextField()
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    pincode = models.IntegerField(null=True, blank=True)
    latitude = models.IntegerField(null=True, blank=True)
    longitude = models.IntegerField(null=True, blank=True)

    class Meta:
        abstract  = True

bloodbank/views.py
import os
from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.views import View
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView 
from django.views.generic.edit import UpdateView 
from django.views.generic.edit import DeleteView
from django.views.generic.detail import DetailView
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic.edit import FormMixin

from accounts_app.form import SignUpForm
from bloodbank.forms import AddBloodForm, CampUpdateForm
from accounts_app.models import User

from bloodbank.models import Blood, BloodBank 
from bloodbank.models import Donation
from bloodbank.models import CampSchedule

from django.db.models import Q
from django.db.models import Count

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib import messages

from blooddrop import settings

from django.db.models import Q
from bloodbank.forms import DonationForm
from bloodbank.forms import CampScheduleForm
from bloodbank.forms import RequestForm
from datetime import timedelta,datetime, timezone
from django.db.models import Max
from django.forms.widgets import HiddenInput

# Create your views here.


class IndexView(DetailView, LoginRequiredMixin, CreateView):   
    model = BloodBank
    form_class = AddBloodForm
    template_name="bloodbank/index_bloodbank.html"
    login_url = "/bloodbank/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        bloodbank = self.object
        
        context['A1'] = bloodbank.bloods.filter(type='A+').count()
        context['A2'] = bloodbank.bloods.filter(type='A-').count()
        context['B1'] = bloodbank.bloods.filter(type='B+').count()
        context['B2'] = bloodbank.bloods.filter(type='B-').count()
        context['AB1'] = bloodbank.bloods.filter(type='AB+').count()
        context['AB2'] = bloodbank.bloods.filter(type='AB-').count()
        context['O1'] = bloodbank.bloods.filter(type='O+').count()
        context['O2'] = bloodbank.bloods.filter(type='O-').count()
        context['total_unit'] = bloodbank.bloods.count()

        return context

    def form_valid(self, form):
        form.instance.user = self.request.user.bloodbank.id
        return super().form_valid(form)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['bloodbank'].widget = HiddenInput()
        form.fields['bloodbank'].initial = self.request.user.bloodbank
        return form
    
    def get_success_url(self):
        return reverse_lazy('index1', kwargs={'pk': self.request.user.bloodbank.id})
         

class BloodBankHistory(ListView):
    model = Donation
    template_name = "bloodbank/bloodbank_history.html"
    context_object_name = 'bloodbank'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(bloodbank_id=self.kwargs['pk'])
        return queryset
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     donations = self.object.donation.all()
    #     donation_data = []
        
    #     for donation in donations:
    #         donor = donation.donor
    #         bloodbank = donation.bloodbank
    #         blood_group = donor.blood_group.blood_group if hasattr(donor, 'blood_group') else None
    #         donation_data.append({
    #             'donation_date': donation.donation_date,
    #             'donor_name': donor.name,
    #             'bloodbank_name': bloodbank.user.name,
    #             'blood_group': blood_group
    #         })
    #     context['donation_data'] = donation_data
    #     return context
    


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'bloodbank/signin_bloodbank.html'
    
    def form_valid(self, form):
        email = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if user is not None:
            if user.is_active:
                login(self.request, user)
                return super().form_valid(form)
        form.add_error(None, 'Invalid email address or password')
        return super().form_invalid(form)
    
    def get_success_url(self):
        return reverse_lazy('index1', kwargs={'pk': self.request.user.bloodbank.id})


class SignupView(CreateView):
    form_class = RequestForm
    template_name = "bloodbank/signup_bloodbank.html"
    success_url = "/user/index/"


class DonorView(ListView):
    model = User
    template_name = "bloodbank/donor_bloodbank.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = User.objects.filter(Q(email__icontains=query)).annotate(
            latest_donation_date=Max('donation__donation_date')
        ).order_by('-latest_donation_date')
        return object_list

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if not self.get_queryset():
            messages.warning(request, 'User does not exist.')
            return redirect('index1', pk=self.request.user.bloodbank.pk)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["timedelta"] = timedelta(days=90)
        context["today"] = datetime.today()
        return context



class DonationCreateView(LoginRequiredMixin, CreateView):
    model = Donation
    template_name = 'bloodbank/donation_form_bloodbank.html'
    form_class = DonationForm
    login_url = '/bloodbank/login/'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['bloodbank'].widget = HiddenInput()
        form.fields['bloodbank'].initial = self.request.user.bloodbank
        return form
    
    def get_success_url(self):
        return reverse_lazy('index1', kwargs={'pk': self.request.user.bloodbank.id})


class CampScheduleView(CreateView):
    model = CampSchedule
    template_name = 'bloodbank/camp_schedule_bloodbank.html'
    form_class = CampScheduleForm
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['bloodbank'].widget = HiddenInput()
        form.fields['bloodbank'].initial = self.request.user.bloodbank
        return form

    def get_success_url(self):
        return reverse_lazy('index1', kwargs={'pk': self.request.user.bloodbank.id})
    
class CampScheduleUpdateView(UpdateView):
    model = CampSchedule
    form_class = CampUpdateForm
    template_name = 'bloodbank/camp_update.html'
    success_url = "/bloodbank/camp-schedule/"

    # def get_queryset(self):
    #     # Get the current date and time
    #     now = datetime.now()
    #     # Filter the queryset to exclude past camps
    #     queryset = CampSchedule.objects.filter(
    #         pk=self.kwargs['pk'],
    #         date__gte=now,
    #     )
    #     return queryset
    

class CampScheduleDeleteView(DeleteView):
    model = CampSchedule
    template_name = 'bloodbank/camp_delete.html'

class CampScheduleDisplayView(ListView):
    model = CampSchedule
    template_name = 'bloodbank/camp_display.html'
    context_object_name = 'camp_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["today"] = datetime.today()
        return context

    def get_queryset(self):
        return CampSchedule.objects.filter(bloodbank=self.request.user.bloodbank)


class UserSignupFromBloodbankView(CreateView):   
    model = User
    template_name="bloodbank/user_signup_bloodbank.html" 
    form_class = SignUpForm

    def get_success_url(self):
        return reverse_lazy('index1', kwargs={'pk': self.request.user.bloodbank.id})

class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect("index")
    

class BloodBankProfileView(DetailView):
    template_name = "bloodbank/display_bloodbank_profile.html"
    model = BloodBank
    context_object_name = 'bloodbank'


class LogoView(TemplateView):
    template_name = 'logo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['logo_url'] = settings.MEDIA_URL + 'path/to/logo.jpg'
        return context


class BloodBankProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'bloodbank/update_profile_bloodbank.html'
    fields = ['name', 'phone_number', 'address', 'city', 'state']

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('bloodbank_profile', kwargs={'pk': self.request.user.bloodbank.id})

   
class BloodBankLogoUpdateView(LoginRequiredMixin, UpdateView):
    model = BloodBank
    template_name = 'bloodbank/update_profile_logo.html'
    fields = ['logo']

    def get_success_url(self):
        return reverse_lazy('bloodbank_profile', kwargs={'pk': self.request.user.bloodbank.id})
    

bloodbank/templates/bloodbank/camp_schedule_bloodbank.html
{% extends "bloodbank/base_bloodbank.html" %}

{% block extra_css %}
<style>

.animated-bg {
   background-size: cover;
  }
  
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: rgba(255, 255, 255, 0.7);
    border-radius: 20px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    opacity: 0.9;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 50px;
  }

  form {
    max-width: 500px; /* adjust this value as needed */
    width: 100%;
  }
  .form-group {
    margin-bottom: 20px;
  }
 
  label {
    display: block;
    font-size: 16px;
    font-weight: bold;
    margin-bottom: 10px;
  }
  
  input[type="text"],
  input[type="password"] {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 16px;
    border-radius: 20px;
    border: none;
    background-color: #eee;
  }
  input[type="date"],
  input[type="time"] {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 16px;
    border-radius: 20px;
    border: none;
    background-color: #eee;
  }
  
  button[type="submit"] {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 16px;
    font-weight: bold;
    border-radius: 20px;
    border: none;
    background-color: #dc3545;
    color: #fff;
  }
    #id_pincode 
    {
    border-radius: 20px;
    border: 1px solid #ccc;
    padding: 8px;
    background-color: #eee;
    width:450px;
    }
    #id_address 
    {
    border-radius: 20px;
    border: 1px solid #ccc;
    padding: 8px;
    background-color: #eee;
    width:450px;
    height:10vh;
    }

    select {
        font-size: 16px;
        color: #333;
        background-color: #eee;
        border: 1px solid #ccc;
        border-radius: 20px;
        padding: 8px;
        width: 450px;
        overflow: hidden; /* add overflow hidden to hide the options by default */
        height: 40px; /* set a fixed height for the dropdown */
        transition: height 0.2s ease; /* add transition to animate the height change */
    }

    select:hover,
    select:focus {
        height: 50px; /* increase the height on hover or focus */
    }
    h1{
      font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }
  
  @media (max-width: 600px) {
    .form-container {
      max-width: 90%;
    }
  }
  
  @keyframes background {
    from { background-color: rgba(0, 0, 0, 0.7); }
    to { background-color: rgba(255, 255, 255, 0.7); }
  }
  .error-message {
    color: red;
  }
</style>
{% endblock extra_css %}

{% block content %}
<body class="animated-bg">
         
    <div class="form-container">

      <form method="post" novalidate>
      <h1 class="text-center fw-bold text-danger">Schedule Camp</h1>
      <br>
        {% csrf_token %}
    
        {{form.as_p}}
    
        <button type="submit" class="btn btn-danger">Schedule</button>
      </form>
    </div>
  
{% endblock content %}

bloodbank/templates/bloodbank/camp_update.html
{% extends "bloodbank/base_bloodbank.html" %}

{% block extra_css %}
<style>

.animated-bg {
   background-size: cover;
  }
  
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: rgba(255, 255, 255, 0.7);
    border-radius: 20px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    opacity: 0.9;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 50px;
  }

  form {
    max-width: 500px; /* adjust this value as needed */
    width: 100%;
  }
  .form-group {
    margin-bottom: 20px;
  }
 
  label {
    display: block;
    font-size: 16px;
    font-weight: bold;
    margin-bottom: 10px;
  }
  
  input[type="text"],
  input[type="password"] {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 16px;
    border-radius: 20px;
    border: none;
    background-color: #eee;
  }
  input[type="date"],
  input[type="time"] {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 16px;
    border-radius: 20px;
    border: none;
    background-color: #eee;
  }
  
  
  button[type="submit"] {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 16px;
    font-weight: bold;
    border-radius: 20px;
    border: none;
    background-color: #dc3545;
    color: #fff;
  }
    #id_pincode 
    {
    border-radius: 20px;
    border: 1px solid #ccc;
    padding: 8px;
    background-color: #eee;
    width:450px;
    }
    #id_address 
    {
    border-radius: 20px;
    border: 1px solid #ccc;
    padding: 8px;
    background-color: #eee;
    width:450px;
    height:10vh;
    }

    select {
        font-size: 16px;
        color: #333;
        background-color: #eee;
        border: 1px solid #ccc;
        border-radius: 20px;
        padding: 8px;
        width: 450px;
        overflow: hidden; /* add overflow hidden to hide the options by default */
        height: 40px; /* set a fixed height for the dropdown */
        transition: height 0.2s ease; /* add transition to animate the height change */
    }

    select:hover,
    select:focus {
        height: 50px; /* increase the height on hover or focus */
    }
    h1{
      font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }
  
  @media (max-width: 600px) {
    .form-container {
      max-width: 90%;
    }
  }
  
  @keyframes background {
    from { background-color: rgba(0, 0, 0, 0.7); }
    to { background-color: rgba(255, 255, 255, 0.7); }
  }
</style>
{% endblock extra_css %}

{% block content %}
<body class="animated-bg">
         
    <div class="form-container">

      <form method="post" novalidate>
      <h1 class="text-center fw-bold text-danger">Update Schedule </h1>
      <br>
        {% csrf_token %}
    
        {{form.as_p}}
    
        <button type="submit" class="btn btn-danger">Update</button>
      </form>
    </div>
  
{% endblock content %}

bloodbank/templates/bloodbank/user_signup_bloodbank.html
{% extends "bloodbank/base_bloodbank.html" %}

{% load static %}

{% block extra_css %}
{{ block.super }}
<style>

    .form-container {
      max-width: 500px;
      margin: 0 auto;
      padding: 50px;
      background-color: rgba(255, 255, 255, 0.7);
      border-radius: 20px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
      opacity: 0.9;
      display: flex;
      justify-content: center;
      align-items: center;
      margin-top: 50px;
      margin-bottom: 150px;
    }

    form {
      max-width: 500px; /* adjust this value as needed */
      width: 100%;
    }

    .form-group {
      margin-bottom: 20px;
    }
  
    label {
      display: block;
      font-size: 16px;
      font-weight: bold;
      margin-bottom: 10px;
    }
    
    button[type="submit"] {
      display: block;
      width: 100%;
      padding: 10px;
      font-size: 16px;
      font-weight: bold;
      border-radius: 20px;
      border: none;
      background-color: #dc3545;
      color: #fff;
    }
    #id_age, 
    #id_weight, 
    #id_pincode, 
    #id_phone_number, 
    #id_name, 
    #id_email, 
    #id_group,
    #id_city,
    #id_state
    {
      border-radius: 20px;
      border: 1px solid #ccc;
      padding: 8px;
      background-color: #eee;
      width:400px;
      height:6vh;
    }
    #id_address 
    {
    border-radius: 20px;
    border: 1px solid #ccc;
    padding: 8px;
    background-color: #eee;
    width:400px;
    height:10vh;
    }

    select {
        font-size: 16px;
        color: #333;
        background-color: #eee;
        border: 1px solid #ccc;
        border-radius: 20px;
        padding: 8px;
        width: 400px;
        margin-left: 0;
        overflow: hidden; /* add overflow hidden to hide the options by default */
        height: 40px; /* set a fixed height for the dropdown */
        transition: height 0.2s ease; /* add transition to animate the height change */
    }

    select:hover,
    select:focus {
        height: 50px; /* increase the height on hover or focus */
    }
    h1{
      font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }
    @media (max-width: 600px) {
      .form-container {
        max-width: 90%;
      }
    }
    
    @keyframes background {
      from { background-color: rgba(0, 0, 0, 0.7); }
      to { background-color: rgba(255, 255, 255, 0.7); }
    }
  </style>
{% endblock extra_css %}

{% block content %}
           
<div class="form-container">
  <form method="post" novalidate>
    <h1 class="text-center fw-bold text-danger">Signup</h1><br>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-danger">Signup</button>
  </form>
</div>

{% endblock content %}